name: Scala CI

on:
  push:
    branches: [ master, 4.x ]
  pull_request:
    branches: [ master, 4.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 14
    - name: Run tests
      run: sbt test
